// ===================================================================
// FACE YOGA EXERCISES — v6.0（68種）
//
// 顔ヨガ／表情筋トレの一般的なメソッドと、8週間の顔ヨガ研究の知見
// （額・眉間・目・口のまわり＝ゆるめる／エラ・あご下＝鍛える）に基づき、
// 部位 × 手法（鍛える・動かす・ゆるめる・呼吸・姿勢）で構成。
//
// 手順の本文とイラストは motion.js（motion-data-*.js）に1本化。
// このファイルは「種目のプロフィール」だけを持つ。
//
// kind: 'training'(鍛える・動かす) / 'stretch'(ゆるめる・マッサージ)
// ===================================================================
import {
  PRESCRIPTION_MAP, EXERCISE_META, EXERCISE_META_EXT,
  CONTRA_LABEL, TIME_OF_DAY_LABEL, TOOLS_LABEL, getMeta, isExerciseAllowed,
} from './prescriptions.js';
export {
  PRESCRIPTION_MAP, EXERCISE_META, EXERCISE_META_EXT,
  CONTRA_LABEL, TIME_OF_DAY_LABEL, TOOLS_LABEL, getMeta, isExerciseAllowed,
};

const svg = (inner) => `<svg viewBox="0 0 80 80" class="ex-svg">${inner}</svg>`;
const face = (extra='') => `
  <ellipse cx="40" cy="44" rx="22" ry="28" fill="#FFE5EC" stroke="#E07A8A" stroke-width="1.5"/>
  <circle cx="32" cy="38" r="2" fill="#0b1530"/>
  <circle cx="48" cy="38" r="2" fill="#0b1530"/>
  ${extra}
`;
const smile = `<path d="M33 55 Q40 58 47 55" stroke="#E07A8A" stroke-width="1.5" fill="none" stroke-linecap="round"/>`;

// 一覧カード用の部位アイコン（手順の本体は motion.js の手順パネル）
const ICON = {
  brow:   svg(face(`<path d="M27 33 Q32 30 37 33 M43 33 Q48 30 53 33" stroke="#3D2A2F" stroke-width="1.5" fill="none"/><path d="M40 29 l0 -5 m-2 2 l2 -2 l2 2" stroke="#FF8FA8" stroke-width="1.5" fill="none" stroke-linecap="round"/>${smile}`)),
  eye:    svg(face(`<circle cx="32" cy="38" r="4.5" fill="none" stroke="#3D2A2F" stroke-width="1.5"/><circle cx="48" cy="38" r="4.5" fill="none" stroke="#3D2A2F" stroke-width="1.5"/>${smile}`)),
  cheek:  svg(face(`<circle cx="27" cy="48" r="6" fill="#FFB7C5" opacity="0.65"/><circle cx="53" cy="48" r="6" fill="#FFB7C5" opacity="0.65"/><path d="M31 55 Q40 51 49 55" stroke="#E07A8A" stroke-width="2" fill="none" stroke-linecap="round"/>`)),
  mouth:  svg(face(`<path d="M31 56 Q40 52 49 56" stroke="#E07A8A" stroke-width="2" fill="none" stroke-linecap="round"/><path d="M31 56 l-3 -3 M49 56 l3 -3" stroke="#FF8FA8" stroke-width="2" stroke-linecap="round"/>`)),
  tongue: svg(face(`<circle cx="40" cy="54" r="7" fill="none" stroke="#FF8FA8" stroke-width="1.5" stroke-dasharray="2 2"/><path d="M47 54 l-2 -2 M47 54 l-2 2" stroke="#FF8FA8" stroke-width="1.5" fill="none"/>`)),
  chin:   svg(face(`<path d="M28 60 Q40 70 52 60" stroke="#E07A8A" stroke-width="2" fill="none"/><path d="M52 60 l4 -2" stroke="#FF8FA8" stroke-width="2" stroke-linecap="round"/>${smile}`)),
  jaw:    svg(face(`<circle cx="25" cy="52" r="5" fill="#FFB7C5" opacity="0.7"/><text x="25" y="55" text-anchor="middle" font-size="9">✋</text>${smile}`)),
  neck:   svg(face(`<path d="M40 70 l0 7 m-3 -3 l3 3 l3 -3" stroke="#FF8FA8" stroke-width="2" fill="none" stroke-linecap="round"/>${smile}`)),
  whole:  svg(face(`<path d="M31 54 Q40 60 49 54" stroke="#E07A8A" stroke-width="2" fill="none" stroke-linecap="round"/><text x="22" y="30" font-size="9">✨</text><text x="52" y="54" font-size="9">✨</text>`)),
  breath: svg(face(`<circle cx="40" cy="58" r="3" fill="none" stroke="#5BA8FF" stroke-width="1.5"/><circle cx="47" cy="62" r="2" fill="none" stroke="#5BA8FF" stroke-width="1"/>${smile}`)),
  relax:  svg(face(`<text x="40" y="26" text-anchor="middle" font-size="9">✋</text><path d="M30 28 L50 28" stroke="#FFB7C5" stroke-width="1.5"/>${smile}`)),
};

export const EXERCISES = {

  // ============== 額・眉間 ==============
  browRaise: {
    id:'browRaise', name:'眉リフト（おでこ）', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.brow,
    purpose:'おでこの力で眉を持ち上げ、目元の重さや眉の左右差を整えます。',
    targets:['おでこ','眉のまわり'],
    cues:{ do:'眉が上がって目がパッと開く感じ', dont:'おでこに深い横ジワを寄せすぎない' },
    why:'おでこの筋肉が使えると、上まぶたが軽くなり、眉の位置や左右差も整いやすくなります。',
  },
  browUpDown: {
    id:'browUpDown', name:'眉の寄せ開き', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.brow,
    purpose:'眉をギュッと寄せる→パッと開くをくり返し、無意識の「眉間の力み」をリセットします。',
    targets:['眉間','おでこ','目のまわり'],
    cues:{ do:'開くときは眉間を左右に広げる意識で', dont:'寄せるときに肩や首まで力を入れない' },
    why:'眉間にシワを寄せるクセは、力みっぱなしが原因。あえて縮めてから広げると、ゆるめる感覚がつかめます。',
  },
  foreheadSmooth: {
    id:'foreheadSmooth', name:'額のシワのばし', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'こわばったおでこをゆるめて、横ジワ・生えぎわのこりをリセットします。',
    targets:['おでこ'],
    cues:{ do:'力を入れず、皮ふが動くくらいやさしく', dont:'ゴシゴシこすらない／爪を立てない' },
    why:'おでこは緊張でこわばりがち。研究でも、額はゆるめるほど硬さが下がり、弾力が上がると報告されています。',
  },
  glabellaRelease: {
    id:'glabellaRelease', name:'眉間のシワのばし', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'眉間の縦ジワのもとになる「力み」を、指でゆるめて流します。',
    targets:['眉間'],
    cues:{ do:'小さく円を描いて、そのあと外へ流す', dont:'強く押しすぎない' },
    why:'眉間は無意識に力が入りやすい場所。ゆるめる習慣がつくと、縦ジワが定着しにくくなります。',
  },
  hairlineLift: {
    id:'hairlineLift', name:'生えぎわリフト', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'生えぎわのこりをほぐして、おでこ全体を上へ引き上げます。',
    targets:['生えぎわ','おでこ'],
    cues:{ do:'最後は手のひらで頭のてっぺんへ引き上げる', dont:'爪を立てない' },
    why:'生えぎわが硬いと、顔全体が下に引っぱられます。頭と顔はつながった1枚の皮ふです。',
  },
  browSolo: {
    id:'browSolo', name:'片眉リフト', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.brow,
    purpose:'片方ずつ眉を動かして、眉の高さの左右差を整えます。',
    targets:['おでこ','眉のまわり'],
    cues:{ do:'上がりにくいほうを多めに', dont:'反対の眉が一緒に上がらないように' },
    why:'眉の左右差は、使えていない側を意識して動かすことで少しずつ縮まります。',
  },

  // ============== 目 ==============
  eyeWideOpen: {
    id:'eyeWideOpen', name:'パッチリ目（まぶた開き）', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.eye,
    purpose:'まぶたを引き上げる力をつけて、目の開きを大きく、眠そうな印象を解消します。',
    targets:['上まぶた'],
    cues:{ do:'眉は動かさず、まぶただけで開く', dont:'眉を上げて代わりにしない' },
    why:'まぶたを引き上げる小さな筋肉が弱ると眠そうな目に。ピンポイントで鍛えると変化が出やすい部位です。',
  },
  binocularPose: {
    id:'binocularPose', name:'双眼鏡のポーズ', category:'training', kind:'training',
    duration:'約1分', equipment:'指・鏡', illustration: ICON.eye,
    purpose:'指で額を固定したまま、目を大きく開く→細めるをくり返し、目のまわり全体を使います。',
    targets:['目のまわり','上まぶた','下まぶた'],
    cues:{ do:'おでこと眉間にシワを寄せないよう指で押さえる', dont:'額の力で目を開かない' },
    why:'額を固定すると、目のまわりの筋肉だけを狙って使えます。顔ヨガの定番ポーズです。',
  },
  lowerLidLift: {
    id:'lowerLidLift', name:'下まぶた締め（涙袋づくり）', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.eye,
    purpose:'下まぶたを使って、目を細める動きで目元をキュッと引き締めます。涙袋づくりにも。',
    targets:['下まぶたのまわり'],
    cues:{ do:'下まぶたの縁が持ち上がって、目が細くなる', dont:'目をギュッとつむらない／眉を動かさない' },
    why:'下まぶたが使えると目元が引き締まり、笑ったときの涙袋も出やすくなります。',
  },
  outerEyeLift: {
    id:'outerEyeLift', name:'目尻すっきり（ウインク）', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.eye,
    purpose:'片目ずつのウインクで目尻まわりを引きしめ、目尻の下がりを引き上げます。',
    targets:['目尻','目のまわり'],
    cues:{ do:'目尻がキュッと上がるのを感じる', dont:'おでこや口が一緒に動かないように' },
    why:'目のまわりをぐるっと囲む筋肉を左右バランスよく使うと、目尻の下がりや左右差が整います。',
  },
  munchFace: {
    id:'munchFace', name:'ムンクの顔', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.eye,
    purpose:'口を「お」にして鼻の下を伸ばし、目線を上へ。目の下のむくみ・クマのケアに向きます。',
    targets:['目の下','鼻の下','ほお'],
    cues:{ do:'顔は正面のまま、目線だけを天井へ', dont:'あごを上げすぎない' },
    why:'顔ヨガの定番ポーズ。目の下が引っぱられて、たまったむくみが動きます。',
  },
  eyeRelease: {
    id:'eyeRelease', name:'目のまわりゆるめ', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'目のまわりの骨のふちに沿って、疲れとこわばりをゆるめます。',
    targets:['目のまわり','こめかみ'],
    cues:{ do:'なでるだけの力で十分', dont:'眼球を押さない／こすらない' },
    why:'目のまわりは研究でも「ゆるめると硬さが下がる」部位。使いすぎた分をリセットします。',
  },
  eyeRoll: {
    id:'eyeRoll', name:'目玉ぐるぐる', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.eye,
    purpose:'顔を動かさず目だけを大きく動かして、目の疲れと動きの幅を取り戻します。',
    targets:['目のまわり'],
    cues:{ do:'顔は固定して、目だけをゆっくり大きく', dont:'速く動かさない／めまいがしたら中止' },
    why:'画面を見続けると目の動きが小さくなります。大きく動かすと血流が戻り、疲れが抜けます。',
  },
  blinkReset: {
    id:'blinkReset', name:'ゆっくりまばたき', category:'training', kind:'stretch',
    duration:'約1分', equipment:'なし', illustration: ICON.relax,
    purpose:'浅くなりがちなまばたきをリセットして、目のまわりの緊張をとります。',
    targets:['まぶた','目のまわり'],
    cues:{ do:'ギュッとせず、そーっと閉じる', dont:'力いっぱいつむらない' },
    why:'画面を見ているとまばたきが浅く・少なくなります。ゆっくり閉じるだけで目元がゆるみます。',
  },

  // ============== 頬 ==============
  cheekLift: {
    id:'cheekLift', name:'頬リフト・スマイル', category:'training', kind:'training',
    duration:'約1分', equipment:'指・鏡', illustration: ICON.cheek,
    purpose:'口角とほおを"斜め上"に引き上げて、笑ったときのほおの高さを取り戻す、リフトの基本トレです。',
    targets:['ほお（笑うとふくらむ、目の下のあたり）'],
    cues:{ do:'ほおの一番高い所が「プクッ」と盛り上がればOK', dont:'眉間にシワを寄せない／首スジに力を入れない' },
    why:'ほおを持ち上げる筋肉は、顔の中で一番早くゆるむ場所。毎日動かすと、ほおの位置が上がります。',
  },
  cheekLiftAssist: {
    id:'cheekLiftAssist', name:'リフトアップ（指で支え）', category:'training', kind:'training',
    duration:'約1分', equipment:'指・鏡', illustration: ICON.cheek,
    purpose:'指でほおを支えながら引き上げて、ほうれい線を内側からのばします。',
    targets:['ほお','ほうれい線'],
    cues:{ do:'口を横に開いて下の歯を見せ、手は軽く上へ', dont:'皮ふを強く引っぱらない' },
    why:'手で軽くサポートすると、自力では届かない高さまでほおが上がり、伸びを覚えられます。',
  },
  cheekPump: {
    id:'cheekPump', name:'頬ふくらませ・へこませ', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.cheek,
    purpose:'ほおをぷくーっと膨らませて、内側から動かします。むくみ・血色ケアにも。',
    targets:['ほおの内側'],
    cues:{ do:'ほおの皮がパンッと張るくらい、しっかり膨らませる', dont:'息を止めて苦しくならない' },
    why:'ふだん使わないほおの内側を動かして血流アップ。顔ヨガの定番です。',
  },
  balloonFace: {
    id:'balloonFace', name:'バルーンフェイス（片ほお）', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.cheek,
    purpose:'片ほおずつ大きく膨らませて、ほうれい線を内側からしっかり伸ばします。',
    targets:['ほおの内側','ほうれい線'],
    cues:{ do:'ほうれい線を内側から伸ばす意識で', dont:'息を止めて苦しくならない' },
    why:'両ほお同時より、片方ずつのほうが内側からの伸びが大きくなります。',
  },
  cheekAir: {
    id:'cheekAir', name:'頬の空気ころがし', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.cheek,
    purpose:'口の中の空気を左右のほおに転がして、内側からストレッチ。左右差ケアにも。',
    targets:['ほおの内側','口のまわり'],
    cues:{ do:'空気でほおの内側がしっかり押し広げられる感じ', dont:'速くしすぎない' },
    why:'左右のほおを均等に動かすことで、内側からのストレッチと左右バランスの調整に役立ちます。',
  },
  cheekBoneMassage: {
    id:'cheekBoneMassage', name:'ほお骨まわりゆるめ', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'ほお骨の下のこわばりをとって、顔を軽くします。',
    targets:['ほお骨のまわり'],
    cues:{ do:'骨の下のくぼみを、鼻の横から耳へ', dont:'強く押しすぎない' },
    why:'ほお骨の下が硬いと、ほおが上がりにくくなります。ゆるめてから鍛えると効率的です。',
  },
  nasolabialStretch: {
    id:'nasolabialStretch', name:'ほうれい線のばし（内側から）', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.cheek,
    purpose:'口の中から、ほうれい線のみぞを内側にふくらませてのばします。',
    targets:['ほうれい線','口まわりの内側'],
    cues:{ do:'みぞが内側から持ち上がる感じ', dont:'息を止めて苦しくならない' },
    why:'ほうれい線は内側からふくらませてのばすと、みぞが浅く見えやすくなります。',
  },
  fishFace: {
    id:'fishFace', name:'フィッシュフェイス', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.cheek,
    purpose:'ほおの内側を吸い込んで、ほおのたるみを引き締めます。',
    targets:['ほお','口のまわり'],
    cues:{ do:'ほおの内側がピンと張る', dont:'苦しくなるほど吸い込まない' },
    why:'膨らませる動きと逆方向。両方やると、ほおを内外の両方から使えます。',
  },

  // ============== 口・唇・鼻の下 ==============
  mouthCornerLift: {
    id:'mouthCornerLift', name:'口角アップ・キープ', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.mouth,
    purpose:'口を開けずに"口角だけ"をキュッと上げてキープ。への字口を上向きグセに変えます。',
    targets:['口の端（口角）'],
    cues:{ do:'口角の"端っこ"だけが上がるのを鏡で確認', dont:'奥歯を噛みしめない／目に力を入れない' },
    why:'口角を上げる力が弱ると、黙っているとき口角が下がって不機嫌そうに見えます。',
  },
  mouthCornerTongue: {
    id:'mouthCornerTongue', name:'口角キュッと（舌で小鼻）', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.mouth,
    purpose:'笑顔をキープしたまま、舌先で小鼻をなめるように動かします。口角とほうれい線の両方に。',
    targets:['口角','ほうれい線','舌'],
    cues:{ do:'口角は上げたままキープ', dont:'首に力を入れない' },
    why:'笑顔の形を保ったまま舌を動かすことで、口まわりを内側と外側から同時に使えます。',
  },
  aiueoTrain: {
    id:'aiueoTrain', name:'あいうえお体操', category:'training', kind:'training',
    duration:'約2分', equipment:'鏡', illustration: ICON.mouth,
    purpose:'「あ・い・う・え・お」と口を大きく動かして、顔ぜんたいの筋肉をまんべんなく起こします。',
    targets:['口のまわり','ほお','あご下'],
    cues:{ do:'1音ずつ「これ以上動かせない」ところまで大きく', dont:'声を出す必要なし／首や肩に力を入れない' },
    why:'顔の筋肉をぜんぶ動かす、ラジオ体操のようなトレ。毎日の土台づくりに。',
  },
  chopstickTrain: {
    id:'chopstickTrain', name:'割り箸トレ', category:'training', kind:'training',
    duration:'約1分', equipment:'割り箸・鏡', illustration: ICON.mouth,
    purpose:'割り箸をくわえて口角を上げる。負荷が上がり、左右差も一目で分かります。',
    targets:['口角','ほお'],
    cues:{ do:'割り箸が水平か鏡でチェック', dont:'強く噛まない' },
    why:'道具があると「どこまで上がったか」が目で分かるので、上達が早くなります。',
  },
  beakPose: {
    id:'beakPose', name:'くちばしポーズ', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.mouth,
    purpose:'くちばしを作ってほおを引き上げ、口元とあごのラインをすっきりさせます。',
    targets:['口のまわり','ほお','フェイスライン'],
    cues:{ do:'ほおを耳から口へ引っ張るイメージ', dont:'息を止めない' },
    why:'呼吸と組み合わせることで、力みを抜きながら口まわりを使えます。',
  },
  upperLipTrain: {
    id:'upperLipTrain', name:'上唇ひきしめ（鼻の下・歯ぐき対策）', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.mouth,
    purpose:'上唇を下へ動かす力をつけて、鼻の下ののびや、笑ったとき歯ぐきが見えすぎるのをケア。',
    targets:['上唇のまわり','鼻の下'],
    cues:{ do:'鼻の下がぐーっと伸びる感覚', dont:'あごや首に力を入れない' },
    why:'上唇を動かす力がつくと、鼻の下が引き締まり、歯ぐきの見えすぎもやわらぎます。',
  },
  lipOpenClose: {
    id:'lipOpenClose', name:'唇の開閉', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.mouth,
    purpose:'あごを動かさず、唇だけをゆっくり開閉。口を閉じる力を取り戻します。',
    targets:['口のまわり'],
    cues:{ do:'あごは動かさず、唇だけで', dont:'歯を食いしばらない' },
    why:'口がぽかんと開くクセは、口を閉じる力の低下が原因のひとつ。地味ですが効きます。',
  },
  lipPucker: {
    id:'lipPucker', name:'口すぼめ・とがらせ', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.mouth,
    purpose:'唇を「う」の形に強くすぼめて、口のまわりをキュッと引き締めます。',
    targets:['口のまわり（唇をぐるっと囲む部分）'],
    cues:{ do:'唇の中心にシワが寄るくらいしっかりすぼめる', dont:'歯を食いしばらない' },
    why:'口のまわりが引き締まると、口元のたるみ予防や、口角の安定につながります。',
  },
  lipRelease: {
    id:'lipRelease', name:'口のまわりゆるめ', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'無意識に入っている口元の力みを、指でゆるめます。',
    targets:['口のまわり'],
    cues:{ do:'小さく円を描いてやさしく', dont:'強く押しすぎない' },
    why:'口のまわりも、研究で「ゆるめると硬さが下がる」部位。鍛えるだけでなくゆるめるのが正解です。',
  },
  bigO: {
    id:'bigO', name:'ビッグO（大きく「オー」）', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.mouth,
    purpose:'口を大きく「オー」の形にして、口のまわりと鼻の下をぐーっと伸ばします。',
    targets:['口のまわり','鼻の下'],
    cues:{ do:'唇は丸く、口のまわりがピンと張る', dont:'あごが痛むときは無理をしない' },
    why:'口元の縦じわは、口まわりが縮んで固まるのが一因。大きく開いて伸ばすと予防になります。',
  },

  // ============== 舌 ==============
  tongueRoll: {
    id:'tongueRoll', name:'舌回し（ベロ回し）', category:'training', kind:'training',
    duration:'約1〜2分', equipment:'なし', illustration: ICON.tongue,
    purpose:'舌を口の中で大きく回して、ほうれい線・口元のたるみ・二重あごをまとめてケア。',
    targets:['口のまわり','ほおの内側','首の前'],
    cues:{ do:'ほおの内側が内側から押される感じ', dont:'肩や首に力を入れない／速く回しすぎない' },
    why:'口のまわりを内側からストレッチできる定番トレ。ほうれい線や口元のもたつき予防に。',
  },
  tonguePress: {
    id:'tonguePress', name:'舌の押し上げ（二重あご対策）', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.tongue,
    purpose:'舌ぜんたいを上あごにぐっと押し当てて、あごの下を内側から引き上げます。',
    targets:['あごの下','舌'],
    cues:{ do:'あごの下（のどの上）に力が入る感じ', dont:'肩を上げない／息を止めない' },
    why:'舌の定位置が上あごになると、あご下がたるみにくくなります。二重あご対策の土台。',
  },
  tongueOut: {
    id:'tongueOut', name:'あっかんべー', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.tongue,
    purpose:'舌を下に伸ばして「ハー」と吐き切る。クマ・くすみ・むくみのケアに向きます。',
    targets:['舌','あごの下','のど'],
    cues:{ do:'舌先に力を入れてとがらせる', dont:'息を止めない' },
    why:'顔ヨガの定番。舌を強く伸ばすと、あご下からのどまで一気に使われ、めぐりが変わります。',
  },
  tongueStretch: {
    id:'tongueStretch', name:'舌ストレッチ', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.tongue,
    purpose:'舌を上下左右に大きく伸ばして、舌の根元とあご下をほぐします。',
    targets:['舌','あごの下'],
    cues:{ do:'届かなくても、届かせるつもりで大きく', dont:'反動をつけない' },
    why:'舌の根元が硬いと、あご下がもたつきます。舌もストレッチできる筋肉です。',
  },
  lionPose: {
    id:'lionPose', name:'ライオンのポーズ', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.whole,
    purpose:'口・舌・目を全部大きく開いて「はーっ」。顔全体とのどがすっきりします。',
    targets:['顔ぜんたい','舌','のど'],
    cues:{ do:'思いきり大きく。人に見られない場所で', dont:'あごが痛むときは無理をしない' },
    why:'ヨガの伝統的なポーズ。顔の筋肉を一度に大きく使い、ストレス発散にもなります。',
  },
  swallowTrain: {
    id:'swallowTrain', name:'ごっくんトレ', category:'training', kind:'training',
    duration:'約1分', equipment:'指', illustration: ICON.tongue,
    purpose:'舌を上あごにつけたまま飲み込む練習。正しい飲み込み方のクセづけです。',
    targets:['あごの下','舌','のど'],
    cues:{ do:'あごの下が硬くなるのを指で確認', dont:'肩を上げない' },
    why:'人は1日に何百回も飲み込みます。その動きが変わると、あご下が大きく変わります。',
  },

  // ============== あご・フェイスライン ==============
  chinTuck: {
    id:'chinTuck', name:'チンタック（二重あご対策）', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.chin,
    purpose:'あごを軽く引いて首の奥を使い、二重あごとフェイスラインを内側から引き上げます。',
    targets:['首の後ろ','あごの下'],
    cues:{ do:'あごを引いて、首の後ろが伸びる', dont:'あごを強く引きすぎない／下を向かない' },
    why:'スマホ姿勢で弱りがちな首の奥を鍛えると、二重あごが引き締まり、姿勢もよくなります。',
  },
  chinPress: {
    id:'chinPress', name:'あご下押し合い', category:'training', kind:'training',
    duration:'約1分', equipment:'指', illustration: ICON.chin,
    purpose:'舌と指で押し合って、あごの下を内側から鍛えます。',
    targets:['あごの下','舌'],
    cues:{ do:'あごの下が硬く盛り上がる', dont:'指で強く押しすぎない' },
    why:'研究でも、あご下は鍛えるほど強くなると報告された部位です。',
  },
  chinMassage: {
    id:'chinMassage', name:'あご下マッサージ', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'あごの先から耳の下へ流して、あご下のもたつき・むくみをケアします。',
    targets:['あごの下','フェイスライン'],
    cues:{ do:'骨のラインに沿って、最後は鎖骨まで流す', dont:'強く押しすぎない' },
    why:'あご下にたまったむくみは、耳の下から鎖骨へ流れます。道筋を作ってあげるイメージです。',
  },
  jawSlide: {
    id:'jawSlide', name:'あご下スッキリ・スライド', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.chin,
    purpose:'下あごを前後・左右に動かして、フェイスラインまわりをほぐし整えます。',
    targets:['あごまわり','フェイスライン'],
    cues:{ do:'ゆっくり大きく、痛みのない範囲で', dont:'速く動かさない／カクッと音が痛む場合は中止' },
    why:'あごの動きがなめらかになると、フェイスラインのこわばりがとれます。',
  },
  mouthOpen: {
    id:'mouthOpen', name:'口を大きく開く（あご）', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.chin,
    purpose:'口を大きく開け閉めして、あごの動きをよくし、こわばりをほぐします。',
    targets:['あごの筋肉','口まわり'],
    cues:{ do:'ゆっくり大きく。あごはまっすぐ上下に', dont:'無理に開けない／痛みや音が出たら中止' },
    why:'あごを大きく動かすと、こわばった筋肉がほぐれ、噛みしめのクセもリセットされます。',
  },
  octopusPose: {
    id:'octopusPose', name:'タコのポーズ', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.neck,
    purpose:'鎖骨を押さえてタコ口で上を向き、首の前を強く伸ばします。二重あご・首のシワに。',
    targets:['首の前','口のまわり','あごの下'],
    cues:{ do:'鎖骨を押さえて、皮ふを下に固定する', dont:'首を反らしすぎない' },
    why:'皮ふを下で固定してから伸ばすので、首の前がしっかり伸びます。顔ヨガの定番ポーズ。',
  },
  chinUpPose: {
    id:'chinUpPose', name:'あご上げポーズ', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.neck,
    purpose:'下唇を上唇にかぶせてあごを上げ、口元と首の前を同時に引き締めます。',
    targets:['首の前','口のまわり','ほうれい線'],
    cues:{ do:'口角を引き上げたままあごを上げる', dont:'首を反らしすぎない／肩を上げない' },
    why:'口元と首を同時に使うと、フェイスラインから胸元（鎖骨のあたり）までつながって引き締まります。',
  },

  // ============== エラ・こめかみ（ゆるめる） ==============
  masseterRelease: {
    id:'masseterRelease', name:'エラほぐし（食いしばりケア）', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.jaw,
    purpose:'食いしばりで硬くなったエラをゆるめて、フェイスラインをすっきり見せます。',
    targets:['エラ（歯を噛みしめると硬くなる部分）'],
    cues:{ do:'「イタ気持ちいい」くらいの強さで', dont:'食いしばったまま押さない／爪を立てない' },
    why:'エラは食いしばりでコリ固まると外側に張り出します。ゆるめるだけで輪郭の印象が変わります。',
  },
  masseterTap: {
    id:'masseterTap', name:'エラのタッピング', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.jaw,
    purpose:'エラを軽くトントン叩いてゆるめます。強く押すのが苦手な方に。',
    targets:['エラ'],
    cues:{ do:'指の腹でリズミカルに軽く', dont:'強く叩かない' },
    why:'押す刺激が苦手でも、軽い振動だけで筋肉はゆるみます。テレビを見ながらでもできます。',
  },
  templeRelease: {
    id:'templeRelease', name:'こめかみほぐし', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'こめかみをゆるめて、食いしばりのこり・目の疲れ・頭の重さをリセットします。',
    targets:['こめかみ（噛むと動く部分）'],
    cues:{ do:'円を描いてやさしく', dont:'強く押しすぎない' },
    why:'こめかみはエラとつながっています。ここをゆるめると食いしばりや頭の緊張がやわらぎます。',
  },
  masseterStretch: {
    id:'masseterStretch', name:'エラのストレッチ', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.jaw,
    purpose:'口を大きく開けて、エラを内側から伸ばします。ほぐしと合わせて。',
    targets:['エラ','あごまわり'],
    cues:{ do:'指でエラの伸びを感じながら', dont:'痛みが出たら中止' },
    why:'ほぐす（押す）と伸ばす（動かす）を両方やると、硬くなったエラがゆるみやすくなります。',
  },

  // ============== 首・肩 ==============
  neckFront: {
    id:'neckFront', name:'首の前のばし', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.neck,
    purpose:'首の前から鎖骨のあたりを伸ばして、二重あご・首のたるみ・フェイスラインを引き締めます。',
    targets:['首の前（あごから鎖骨まで）'],
    cues:{ do:'首の前〜鎖骨に縦のスジが浮く感じ', dont:'首を反らしすぎない／肩を上げない' },
    why:'首の前の筋肉は皮ふと直接つながり、たるみに直結します。伸ばして使うと締まります。',
  },
  neckSide: {
    id:'neckSide', name:'首の横のばし', category:'training', kind:'stretch',
    duration:'約1分', equipment:'なし', illustration: ICON.neck,
    purpose:'首の横を伸ばして、こり・むくみをとり、首まわりをすっきりさせます。',
    targets:['首の横'],
    cues:{ do:'伸ばす側の肩は下げたまま', dont:'頭を強く引っ張らない／反動をつけない' },
    why:'首の横のこりをとると血流がよくなり、顔のむくみやフェイスラインのだぶつきもすっきりします。',
  },
  neckBack: {
    id:'neckBack', name:'首の後ろのばし', category:'training', kind:'stretch',
    duration:'約1分', equipment:'なし', illustration: ICON.neck,
    purpose:'下を向きがちな首の後ろをゆるめて、頭の重さをリセットします。',
    targets:['首の後ろ'],
    cues:{ do:'手は乗せるだけ。重みで伸ばす', dont:'引っ張らない／反動をつけない' },
    why:'スマホで下を向く時間が長いほど、首の後ろは硬くなります。顔のたるみの土台にも関係します。',
  },
  neckDiagonal: {
    id:'neckDiagonal', name:'首の斜め後ろのばし', category:'training', kind:'stretch',
    duration:'約1分', equipment:'なし', illustration: ICON.neck,
    purpose:'斜め下を向いて、まっすぐ横に倒すのとは違う場所を伸ばします。',
    targets:['首の斜め後ろ'],
    cues:{ do:'脇のほうを見るように斜め下へ', dont:'強く引っ張らない' },
    why:'首の筋肉は方向によって伸びる場所が違います。斜めを足すと、深いこりに届きます。',
  },
  neckIso: {
    id:'neckIso', name:'首の押し合いトレ', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.neck,
    purpose:'手と頭で押し合って、首を動かさずに首まわりを鍛えます。',
    targets:['首まわり'],
    cues:{ do:'首が動かず、力だけ入っているのが正解', dont:'息を止めない／痛みが出たら中止' },
    why:'8週間の顔ヨガ研究にも含まれていた種目。首を痛めずに支える力をつけられます。',
  },
  neckMassage: {
    id:'neckMassage', name:'首すじ流し', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'耳の下から鎖骨へ流して、顔のむくみの通り道を開けます。',
    targets:['首すじ'],
    cues:{ do:'なでるくらいの強さで、上から下へ', dont:'強く揉まない' },
    why:'顔のむくみは首を通って流れます。研究プログラムでも首マッサージが組み込まれていました。',
  },
  clavicleLymph: {
    id:'clavicleLymph', name:'鎖骨ゆるめ', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'顔のむくみが最後に流れ着く、鎖骨の上のくぼみをゆるめます。',
    targets:['鎖骨の上','首の付け根'],
    cues:{ do:'指の腹で、軽く押さえるだけ', dont:'強く押さない' },
    why:'ここが詰まっていると、顔をいくら流しても行き先がありません。仕上げにおすすめです。',
  },
  shoulderRoll: {
    id:'shoulderRoll', name:'肩まわし', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.neck,
    purpose:'肩を大きくまわして下げ、首と顔を軽くします。',
    targets:['肩','首の付け根'],
    cues:{ do:'ひじで大きな円を描く', dont:'力任せに速く回さない' },
    why:'肩が上がっていると、首も顔も引っぱられます。顔トレの前後にやると効果が出やすくなります。',
  },

  // ============== 全体・呼吸・姿勢・左右差 ==============
  fullFlow: {
    id:'fullFlow', name:'全表情フロー', category:'training', kind:'training',
    duration:'約2分', equipment:'鏡', illustration: ICON.whole,
    purpose:'顔ぜんたいの動きを一連の流れでつなげ、顔の筋肉をぜんぶ目覚めさせる総合トレ。',
    targets:['顔ぜんたい'],
    cues:{ do:'1つ1つの動きを大きく、流れるように', dont:'力みすぎず、リズムよく' },
    why:'顔ぜんたいを連動させて動かすと、使い忘れの筋肉が減り、表情が生き生きします。',
  },
  faceRelax: {
    id:'faceRelax', name:'顔ぜんたいリラックス', category:'training', kind:'stretch',
    duration:'約1分', equipment:'なし', illustration: ICON.relax,
    purpose:'ギュッと縮めて、ぱーと広げる。1日の終わりのこわばりリセットに。',
    targets:['顔ぜんたい'],
    cues:{ do:'「ゆるめる」感覚を大切に', dont:'頑張りすぎない' },
    why:'使った筋肉をゆるめると、こわばりが残らず、血色もよくなります。就寝前にもおすすめ。',
  },
  breathGlow: {
    id:'breathGlow', name:'深呼吸フェイスグロー', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.breath,
    purpose:'深い呼吸で顔まわりの血流を上げ、血色・つやをアップさせます。',
    targets:['顔の血流','表情全体'],
    cues:{ do:'吐く息を長く。顔がぽかぽかしてきたらOK', dont:'息を止めて無理しない／めまいがしたら中止' },
    why:'深い呼吸は自律神経を整え、顔まわりの血流を促します。むくみやくすみのケアにも。',
  },
  diaphragmBreath: {
    id:'diaphragmBreath', name:'お腹の呼吸', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.breath,
    purpose:'お腹で深く呼吸して、顔の余計な力みを抜きます。顔トレの前の準備運動に。',
    targets:['呼吸','顔の力み'],
    cues:{ do:'お腹に当てた手が前に出る／胸の手は動かさない', dont:'肩で息をしない' },
    why:'8週間の顔ヨガ研究も、この呼吸から始まる構成でした。力みが抜けると顔トレの効きが変わります。',
  },
  bloodFlowPose: {
    id:'bloodFlowPose', name:'血行促進ポーズ', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.breath,
    purpose:'顔のパーツを中心に集めてから、勢いよく吐き出す。くすみ・血行のケアに。',
    targets:['顔ぜんたい','血流'],
    cues:{ do:'思いきりギュッと縮めてから、パッと放す', dont:'息を止めない' },
    why:'縮める→ゆるめるの落差で血流が動きます。顔色がすぐ変わるのが分かります。',
  },
  freshFacePose: {
    id:'freshFacePose', name:'フレッシュ顔ポーズ', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.whole,
    purpose:'「わー」→「お」と動かして、顔ぜんたいを目覚めさせます。朝のスイッチ入れに。',
    targets:['顔ぜんたい','口のまわり','目のまわり'],
    cues:{ do:'ひとつずつ大きく', dont:'あごが痛むときは無理をしない' },
    why:'寝起きの動かない顔を、短時間で起こせます。朝の1分にちょうどいいポーズです。',
  },
  faceMassage: {
    id:'faceMassage', name:'顔全体マッサージ', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'額・目・ほお・あご・首を、内から外へ順に流す仕上げのケア。',
    targets:['顔ぜんたい','首'],
    cues:{ do:'乳液やクリームをつけて滑りをよくする', dont:'こすらない／引っぱらない' },
    why:'研究プログラムにも顔全体マッサージが組み込まれていました。トレの後にやると流れが整います。',
  },
  postureFace: {
    id:'postureFace', name:'姿勢×顔つながり', category:'training', kind:'training',
    duration:'約1分', equipment:'なし', illustration: ICON.neck,
    purpose:'背すじと首を整えて、顔がたるみにくい「土台」を作ります。',
    targets:['姿勢','首まわり','フェイスライン'],
    cues:{ do:'耳・肩・お尻が縦に一直線', dont:'あごが前に出ない／肩に力を入れない' },
    why:'猫背やスマホ姿勢は顔のたるみの隠れた原因。姿勢が整うと顔トレの効果も出やすくなります。',
  },
  symmetrySmile: {
    id:'symmetrySmile', name:'左右対称スマイル', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.mouth,
    purpose:'鏡を見ながら左右均等に笑顔を作り、表情の左右差を整えます。',
    targets:['口角','ほお','表情全体'],
    cues:{ do:'鏡で左右の口角の高さを毎回チェック', dont:'上がりやすい側だけで笑わない' },
    why:'笑顔の左右差は、弱い側を意識して使うことで少しずつ整います。鏡でのセルフチェックが近道。',
  },
  oneSideSmile: {
    id:'oneSideSmile', name:'片側スマイル（弱い側を強化）', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.mouth,
    purpose:'上がりにくい側の口角だけを集中的に鍛えて、左右差を積極的に是正します。',
    targets:['弱い側の口角','ほお'],
    cues:{ do:'弱い側だけをピンポイントで動かす', dont:'反対側や首が一緒に動かないように' },
    why:'左右差は「弱い側を多めに使う」ことで縮まります。バランスを整える仕上げのトレ。',
  },
  smileHold: {
    id:'smileHold', name:'最高の笑顔キープ', category:'training', kind:'training',
    duration:'約1分', equipment:'鏡', illustration: ICON.whole,
    purpose:'自分の一番いい笑顔を10秒キープ。笑顔の「持久力」をつけます。',
    targets:['口角','ほお','目のまわり'],
    cues:{ do:'ほおがプルプルしてきたら効いている', dont:'奥歯を噛みしめない' },
    why:'笑顔は一瞬なら誰でも作れます。キープできる力がつくと、写真でも自然な笑顔が出せます。',
  },

  // ============== 網羅性強化（v6.2 追加） ==============
  earYoga: {
    id:'earYoga', name:'耳ヨガ（引っぱって回す）', category:'training', kind:'stretch',
    duration:'約1分', equipment:'なし', illustration: ICON.whole,
    purpose:'耳を引っぱって回し、顔まわりの巡りを一気に良くします。むくみ・くすみ・こめかみのこわばりに。',
    targets:['耳のまわり','こめかみ','顔全体の巡り'],
    cues:{ do:'痛気持ちいい強さで、呼吸を続けて', dont:'痛いほど強く引っぱらない' },
    why:'耳のまわりには血管やリンパが集まり、動かすと顔全体の巡りが上がります。手ぶらでどこでもできるのが利点です。',
  },
  oneSideRelease: {
    id:'oneSideRelease', name:'硬い側をゆるめる（片側リリース）', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'左右差の「張っている側」だけを、こめかみ→エラ→首すじの順にゆるめます。噛み癖・片側の緊張リセットに。',
    targets:['こめかみ（硬い側）','エラ（硬い側）','首すじ（硬い側）'],
    cues:{ do:'硬いと感じる側だけ、多めに', dont:'痛いほど強く押さない' },
    why:'左右差は「弱い側を鍛える」だけでなく「張っている側をゆるめる」と早く整います。噛み癖のある側は特に硬くなりがちです。',
  },
  faceLymphDrain: {
    id:'faceLymphDrain', name:'顔リンパ流し（目の下→鎖骨）', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.whole,
    purpose:'目の下→耳の前→あご下→鎖骨の順に、むくみを流す道すじを追ってドレナージュします。',
    targets:['目の下','耳の前','あご下','鎖骨'],
    cues:{ do:'なでるだけの弱い圧で、最後は必ず鎖骨へ', dont:'強くこすらない（皮ふが薄い）' },
    why:'顔のむくみは、最後に鎖骨のリンパ節へ流すのがコツ。道すじを追うことで水分・老廃物が抜けやすくなります。',
  },
  cornerDepressorRelease: {
    id:'cornerDepressorRelease', name:'口角の下ゆるめ（への字ケア）', category:'training', kind:'stretch',
    duration:'約1分', equipment:'指', illustration: ICON.relax,
    purpose:'口角を下へ引っぱる筋肉（への字のもと）と、あご先の力みをゆるめます。口角下がり・梅干しジワに。',
    targets:['口角の下','あご先'],
    cues:{ do:'下から上へ、やさしく引き上げるように', dont:'あご先に力を入れて固めない' },
    why:'口角下がりは「上げる筋肉が弱い」だけでなく「下げる筋肉が張っている」ことも一因。ゆるめると口角が上がりやすくなります。',
  },

};
